### ISSUE TITLE
v2.0.4-algo51 branch does not compile on mac os

### ISSUE THREAD

**Issue by VictorLux** [ZclassicCommunity/zclassic#19]
Hi,

Go a build error on mac os.

need to apply the zcash fix.
Got the same build error : https://github.com/zcash/zcash/issues/3860

Fix is there : https://github.com/zcash/zcash/commit/33548140d9ab2e2d57e8c3278e2ec7b70d346e92

Thanks.

**Comment by matt6412** [comment]
did you try to build with the zcash fix commit ( https://github.com/zcash/zcash/commit/33548140d9ab2e2d57e8c3278e2ec7b70d346e92 ) and it worked on mac os?

**Comment by VictorLux** [comment]
Yes already updated and build is ok with the fix;
