### ISSUE TITLE
2.0.4 deprecated

### ISSUE THREAD

**Issue by matt6412** [ZclassicCommunity/zclassic#21]
@Skellers21 do you know what command needs to be entered into the conf file? something like disabledeprecation=2.0.4-1
disabledeprecation=2.0.4 (has to correspond with the version of zcash running and I think the attribute --dirty needs to be possibly added?)

I am in talks with the zel team because their full node for zcl is failing because it is now deprecated, but they are saying bypass deprecation on current zclassic versions dont work?

**Comment by matt6412** [comment]
you guys need to alter the deprecation policy so you can set to ignore or update zclassic, when the fork was made from @skellers21 he copied zcash and removed the founders fee and must have not altered the security policy


https://electriccoin.co/blog/new-release-1-1-2/

**Comment by matt6412** [comment]
update: this issue doesnt occur on full node clients, its occuring on zelcore wallets that run full nodes.

**Comment by tedy5** [comment]
> update: this issue doesnt occur on full node clients, its occuring on zelcore wallets that run full nodes.

Are you sure it doesn't?

Warning from Zclassic full node:
Warning: This version will be deprecated at block height 559501, and will automatically shut down. You should upgrade to the latest version of Zcash.

**Comment by matt6412** [comment]
Only occurs on zel full node wallets, they need to update their binaries

**Comment by tedy5** [comment]
Warning I pasted above comes from https://github.com/ZclassicCommunity/zclassic/blob/master/src/deprecation.cpp#L41

**Comment by matt6412** [comment]
The difference was that on zel full node wallets it was beyond deprecation height and would shut down.  Now with zclassic 2.0.4 it is warning about the deprecation policy approaching
