### ISSUE TITLE
z_shieldcoinbase always fails with mandatory-script-verify-flag-failed error

### ISSUE THREAD

**Issue by slavikus** [ZclassicCommunity/zclassic#27]
### Describe the issue
An attempt to do z_shieldcoinbase always fails with mandatory-script-verify-flag-failed error.

### Can you reliably reproduce the issue?

```
# zcl-cli z_gettotalbalance
{
  "transparent": "375.00147239",
  "private": "0.00200846",
  "total": "375.00348085"
}

# zcl-cli z_shieldcoinbase t1MLte2bsWTjcY4BYZkdtz2uTqpPdoB3qmy zcBj6YcL4tWD3K67CZpxJPL3pjwQPAZvpjq3LP9QH2VpE9GF7FUs6GLbMBUzwgMQ71biekxsL9ZqLgsKdKkrvJgEdmPqMHS
{
  "remainingUTXOs": 0,
  "remainingValue": 0.00000000,
  "shieldingUTXOs": 30,
  "shieldingValue": 375.00147239,
  "opid": "opid-c98d5f6c-56ee-4b98-99f8-af8d2c25ef64"
}

# zcl-cli z_getoperationstatus
[
  {
    "id": "opid-f676e31c-a50f-4fed-bbcf-85225e1abf0e",
    "status": "failed",
    "creation_time": 1567220208,
    "error": {
      "code": -26,
      "message": "16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"
    },
    "method": "z_sendmany",
    "params": {
      "fromaddress": "t1MLte2bsWTjcY4BYZkdtz2uTqpPdoB3qmy",
      "amounts": [
        {
          "address": "zcBj6YcL4tWD3K67CZpxJPL3pjwQPAZvpjq3LP9QH2VpE9GF7FUs6GLbMBUzwgMQ71biekxsL9ZqLgsKdKkrvJgEdmPqMHS",
          "amount": 375.00137239
        }
      ],
      "minconf": 1,
      "fee": 0.0001
    }
  },
  {
    "id": "opid-c98d5f6c-56ee-4b98-99f8-af8d2c25ef64",
    "status": "failed",
    "creation_time": 1567222011,
    "error": {
      "code": -26,
      "message": "16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"
    },
    "method": "z_shieldcoinbase",
    "params": {
      "fromaddress": "t1MLte2bsWTjcY4BYZkdtz2uTqpPdoB3qmy",
      "toaddress": "zcBj6YcL4tWD3K67CZpxJPL3pjwQPAZvpjq3LP9QH2VpE9GF7FUs6GLbMBUzwgMQ71biekxsL9ZqLgsKdKkrvJgEdmPqMHS",
      "fee": 0.00010000
    }
  }
]
```

**opid-f676e31c-a50f-4fed-bbcf-85225e1abf0e** is the result of doing the same with z_sendmany. The issue persists and we are unable to shield newly mined coins to distribute them to the miners.

**Comment by slavikus** [comment]
Removing wallet.dat and reimporting the keys did not solve the problem.

Rolling node one version back resolves the issue.

**Comment by VictorLux** [comment]
Hi,

I build 2.0.5 on Mac Os, and reproduced the same error with the z_sendmany command.
 z_sendmany "t1JxpaLp1izYEmSPTU72jMoHciZTMYPJqwd"  '[{"address": "zcD7YYSEGTnZtEuPDddGmKL3uNjSBT88CLqaaVbZLqM26TKWutJPka2uW9NemSQYSE4mp7kLmB9uQKcAX2UFquTXmwPi9ey" ,"amount": 0.5}]'

{
    "id": "opid-ce3ef1f9-5d5c-445c-a491-f37fd5240cf4",
    "status": "failed",
    "creation_time": 1567364509,
    "error": {
      "code": -26,
      "message": "16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"
    },
    "method": "z_sendmany",
    "params": {
      "fromaddress": "t1JxpaLp1izYEmSPTU72jMoHciZTMYPJqwd",
      "amounts": [
        {
          "address": "zcD7YYSEGTnZtEuPDddGmKL3uNjSBT88CLqaaVbZLqM26TKWutJPka2uW9NemSQYSE4mp7kLmB9uQKcAX2UFquTXmwPi9ey",
          "amount": 0.5
        }
      ],
      "minconf": 1,
      "fee": 0.0001
    }

**Comment by VictorLux** [comment]
I changed in deprecation.h from your version 
static const int APPROX_RELEASE_HEIGHT = 585318;
to
static const int APPROX_RELEASE_HEIGHT = 582000;

seems it works(the Approx_release_height is not only used for deprecation(check zcash git))

 ./zclassic-cli z_sendmany "t1JxpaLp1izYEmSPTU72jMoHciZTMYPJqwd"  '[{"address": "zcD7YYSEGTnZtEuPDddGmKL3uNjSBT88CLqaaVbZLqM26TKWutJPka2uW9NemSQYSE4mp7kLmB9uQKcAX2UFquTXmwPi9ey" ,"amount": 0.5}]'

[
  {
    "id": "opid-733b9bb6-d063-4528-a2d5-476de4357727",
    "status": "executing",
    "creation_time": 1567369386,
    "method": "z_sendmany",
    "params": {
      "fromaddress": "t1JxpaLp1izYEmSPTU72jMoHciZTMYPJqwd",
      "amounts": [
        {
          "address": "zcD7YYSEGTnZtEuPDddGmKL3uNjSBT88CLqaaVbZLqM26TKWutJPka2uW9NemSQYSE4mp7kLmB9uQKcAX2UFquTXmwPi9ey",
          "amount": 0.5
        }
      ],
      "minconf": 1,
      "fee": 0.0001
    }
  }
]

./zclassic-cli z_getoperationstatus
[
  {
    "id": "opid-733b9bb6-d063-4528-a2d5-476de4357727",
    "status": "success",
    "creation_time": 1567369386,
    "result": {
      "txid": "2212df707d78f1d12e3c6a021bba9a91d02a5652563346c0a41d2f98f0718384"
    },
    "execution_secs": 20.909366,
    "method": "z_sendmany",
    "params": {
      "fromaddress": "t1JxpaLp1izYEmSPTU72jMoHciZTMYPJqwd",
      "amounts": [
        {
          "address": "zcD7YYSEGTnZtEuPDddGmKL3uNjSBT88CLqaaVbZLqM26TKWutJPka2uW9NemSQYSE4mp7kLmB9uQKcAX2UFquTXmwPi9ey",
          "amount": 0.5
        }
      ],
      "minconf": 1,
      "fee": 0.0001
    }
  }
]
