### ISSUE TITLE
Blockchain stuck, need another fork

### ISSUE THREAD

**Issue by rewrewby** [ZclassicCommunity/zclassic#33]
After fork due high difficulty (it didn't reset) ZClassic blockchain stuck.

Block times since fork:
```
585318 - 183 minutes
585319 - 526 minutes
585320 - 658 minutes
585321 - 1403 minutes
585322 - 3291 minutes passed and still not found
```

Due to bad difficulty algorithm the following blocks will have these difficulties:
```
585323 - 499849
585324 - 372264 (-25% drop)
585325 - 366409
585326 - 360156
585327 - 352957
585328 - 345914
...
585335 - 288218
585336 - 278904
```

So it will takes MONTHS to return to "normal" difficulty. You need a fork from 585323 (or 585324) block with adjusted difficulty (set it to 1)  to make blockchain live again.

**Comment by matt6412** [comment]
A fork could fix it (although slightly embarrassing), or an emergency rescue squad of miners rented out with someone willing to shell out the $$ for the good of the cause. I could see a combo of a whale (bits?)  offering a very high multiplier for xxx blocks until the difficulty is back to normal, that would help , and than the other whale with a high stake in the chain paying for the hash on M.R.R. ( @heyrhett ) @htrap

**Comment by rewrewby** [comment]
@matt6412, currently MRR doesn't have enought hashrate to even found 1 block per day.

**Comment by matt6412** [comment]
MRR has whatever people want to mine, theres too many gpus out there and nothing to mine, im sure they can deliver something effective

**Comment by matt6412** [comment]
well there ya go, new fork. case closed
