### ISSUE TITLE
2.0.5-1 full node not sync at 100% and zclassic-cli getblocktemplate return -10 error code

### ISSUE THREAD

**Issue by VictorLux** [ZclassicCommunity/zclassic#34]
### Describe the issue
After installation (block height 585321) on a new VPS and with master branch(2.0.5-1) blockchain not synced at 100% and zclassic-cli getblocktemplate return -10 error code.

#### If so, please list the steps to reproduce below:
1. install 2.0.5-1 build and compile
2. start zclassicd
3. when it reached the current high block height on bc execute zclassic-cli getblocktemplate

### Expected behaviour
Sync should be at 100% and zclassic-cli getblocktemplate should return several values

### Actual behaviour + errors
zclassic-cli getblocktemplate
error code: -10
error message:
ZClassic is downloading blocks...

See screenshot

### The version of zclassicd you were using:
ZClassic Daemon version v2.0.5-1-845a2d8d6

<img width="616" alt="Capture d’écran 2019-09-08 à 23 03 09" src="https://user-images.githubusercontent.com/37399521/64494575-035b9280-d28f-11e9-9e69-28f663b03194.png">

**Comment by rewrewby** [comment]
Confirmed.

```
root@ubuntu:~# zclassic-cli getinfo
{
  "version": 2000551,
  "protocolversion": 170009,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 585321,
  "timeoffset": 0,
  "connections": 14,
  "proxy": "",
  "difficulty": 508858.8011788576,
  "testnet": false,
  "keypoololdest": 1511131242,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
root@ubuntu:~# zclassic-cli getblocktemplate
error code: -10
error message:
ZClassic is downloading blocks...
```

**Comment by AlexSpain** [comment]
zclassic-2.0.5-2
 ./zclassic-cli getinfo
{
  "version": 2000552,
  "protocolversion": 170010,
  "walletversion": 60000,
  "balance": 294.00000000,
  "blocks": 585321,
  "timeoffset": 0,
  "connections": 6,
  "proxy": "",
  "difficulty": 508858.8011788576,
  "testnet": false,
  "keypoololdest": 1568903792,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
Stuck sync at 585321 2 days waiting peers.
