### ISSUE TITLE
Sendrawtransaction fails on latest version v2.0.5-2

### ISSUE THREAD

**Issue by redred77** [ZclassicCommunity/zclassic#37]
### Can you reliably reproduce the issue?
1. run zclassicd v2.0.5-2
2. generate hex data for transaction.
3. call sendrawtransaction api with generated hex data.
4. it fails

### Expected behaviour
Tell us what should happen
It should work.
It worked fine before the latest hardfork upgrade.

### Actual behaviour + errors
Tell us what happens instead including any noticable error output (any messages displayed on-screen when e.g. a crash occurred)

got this message.
{"code":-26,"message":"16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"}
v2.0.5-2

### The version of Zcash you were using:
Run `zcashd --version` to find out
Zclassic RPC client version v2.0.5-2-694f53fd9

### Machine specs:
- OS name + version: Ubuntu
- CPU: Intel 16core
- RAM: 32gb
- Disk size: 1tb
- Disk Type (HD/SDD): ssd
- Linux kernel version (uname -a):
Linux wallet_daemons 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Compiler version (gcc -version):
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by cryptoprofutonium** [comment]
Can you share with me the output of 
`zclassic-cli getblockchaininfo`

**Comment by redred77** [comment]
Sure. here it is.

```
{
  "chain": "main",
  "blocks": 586569,
  "headers": 586569,
  "bestblockhash": "00000034f7810cf7b2fc47bcc79fe44bbbb7905830a52d1db18077a98acde371",
  "difficulty": 3130.582697735171,
  "verificationprogress": 0.9999969424598415,
  "chainwork": "000000000000000000000000000000000000000000000000000b30cd75ced441",
  "pruned": false,
  "size_on_disk": 3923044096,
  "commitments": 968552,
  "valuePools": [
    {
      "id": "sprout",
      "monitored": true,
      "chainValue": 11500.54680959,
      "chainValueZat": 1150054680959
    },
    {
      "id": "sapling",
      "monitored": true,
      "chainValue": 8267.75515139,
      "chainValueZat": 826775515139
    }
  ],
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "enforce": {
        "status": true,
        "found": 4000,
        "required": 750,
        "window": 4000
      },
      "reject": {
        "status": true,
        "found": 4000,
        "required": 950,
        "window": 4000
      }
    }
  ],
  "upgrades": {
    "5ba81b19": {
      "name": "Overwinter",
      "activationheight": 476969,
      "status": "active",
      "info": "See https://z.cash/upgrade/overwinter.html for details."
    },
    "76b809bb": {
      "name": "Sapling",
      "activationheight": 476969,
      "status": "active",
      "info": "See https://z.cash/upgrade/sapling.html for details."
    },
    "821a451c": {
      "name": "Bubbles",
      "activationheight": 585318,
      "status": "active",
      "info": "See ZClassic for details."
    },
    "930b540d": {
      "name": "Bubbly",
      "activationheight": 585322,
      "status": "active",
      "info": "See ZClassic for details."
    }
  },
  "consensus": {
    "chaintip": "930b540d",
    "nextblock": "930b540d"
  }
}
```

**Comment by cryptoprofutonium** [comment]
If you are using any external tool to sign the transaction, note that you need to use the new branch id 0x930b540d, also could you clarify, what steps do you use to generate hex data for transaction in your step `2 generate hex data for transaction`.

**Comment by redred77** [comment]
Changing branchid fixed issue. Thanks!
We generate hex data for transaction from offline machine which is totally isolated from zclassic wallet daemon. We use bitcoinjs-lib like projects to manually generate hex code.
