### ISSUE TITLE
Bumping this

### ISSUE THREAD

**Issue by Coinomatron** [ZclassicCommunity/zclassic#56]
Coinomi can't compile the latest release.

https://www.reddit.com/r/COINOMI/comments/tjcpep/i_havent_got_connection_on_zclassic_on_coinomi/

**Comment by Shinoa-Fores** [comment]
Fixed with v2.1.1-5 release: https://github.com/ZclassicCommunity/zclassic/releases/tag/v2.1.1-5

**Comment by Coinomatron** [comment]
Thanks!
